language: ruby
rvm:
- 2.5.1
script:
- bundle exec rails db:migrate
- bundle exec rspec -fd spec
deploy:
  provider: heroku
  api_key:
    secure: QIi76ssXwwlHBJJII45u4qXT1esjDlz4RBITE8P1TZlP4y48jKqhJRLVR0zcE6es+kQYZz0fvo3UAejsBn63jYrhsmNt7YPwRz9M9lhlMzO9BqwmfB/erGjfvA+0nQb0SrY1NqSe35X2QximD5RPLOpd3e2g5YHytmbXTn/sL0UwfDwJ95n2xrGSlrXdux949vvJdy0JghBc2+v0TeesjtCHK26V+l/vAzTgN8yCc1vNdT14tds/ee4j+UqWZveW1A5l1dyUWtRZ458Ho5FOyb1PYrv/PB4hQOTHgsWowXpLFrlmlGnUwPi+i+CAO7QXFq+rPf0qKx9uMCiAuetHk67Ew5ukV+KjxKIwhGEowDY5etJalMlIo+2E+d5ebET5YZSATDud8iGwotc+5og39/iF4z7oj5FkZ6MfS9F0K/ZJ5Z36bB+b4rf6GRCk3xBmzKhvp317ccBKbRLXj1r6D8cUoLle/FCxZap/I4a9Boctz0cwEc4ZVfkhz4p4iZ/OUurFNj2M1fw5kVk96bpcNIlEQqI6QcFZtT8e0m+FAu3VBqlhGX+7ykZGnXrlllfODF3v1KL2dtSuVB4mkgrGN9kjZwjNM9RG8DXjOp1rEoPQ7TxxjGHzXODp74AbPbUSZl4K7VteFJW5d5YMPR4ehwfnyxkPhnNr4VYAS/K2r/w=
